# Generated by Django 3.2 on 2021-04-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='yearofbirth',
            new_name='age',
        ),
    ]
